### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by kritikakriti** [manuelaguadomtz/pyeer#5]
Hello,
Thank you for the repository. It is a great help.
However, please tell me why I am getting this value error. I have tried the code with histogram format genuine scores and imposter scores but I get the following error.
Following is the command I have used and the error I get :
`!geteerinf -p "/content/drive/MyDrive/data/" -i "/content/drive/MyDrive/data/imposter.txt" -g "/content/drive/MyDrive/data/genuine_score.txt" -e "exp2" -ht -sp "/content/drive/MyDrive/data/EER1/"`
```
exp2: Loading genuine scores file...
Traceback (most recent call last):
  File "/usr/local/bin/geteerinf", line 8, in <module>
    sys.exit(get_eer_info_cmd())
  File "/usr/local/lib/python3.6/dist-packages/pyeer/eer_info.py", line 127, in get_eer_info_cmd
    gen_scores = [__get_score(line) for line in tf]
  File "/usr/local/lib/python3.6/dist-packages/pyeer/eer_info.py", line 127, in <listcomp>
    gen_scores = [__get_score(line) for line in tf]
  File "/usr/local/lib/python3.6/dist-packages/pyeer/eer_info.py", line 45, in __get_score
    return float(sline[-1])
ValueError: could not convert string to float: 
```
please help, thank you in advance.

**Comment by manuelaguadomtz** [comment]
Hi, it seems that the format of your scores file is incorrect. Please verify that the format corresponds to the format of the example files in [https://github.com/manuelaguadomtz/pyeer/tree/master/pyeer/example_files/hist](https://github.com/manuelaguadomtz/pyeer/tree/master/pyeer/example_files/hist). Particularly, it seems that you may have some non-float values in the last column of your score files.

**Comment by kritikakriti** [comment]
Thank you for your consideration. I have figured it out .
