### ISSUE TITLE
get_eer_stats for similarity scores

### ISSUE THREAD

**Issue by MonicaSai7** [manuelaguadomtz/pyeer#6]
With what parameters should `get_eer_stats(gen_scores, imp_scores, hformat=False, ds_scores=False)` be called to get metrics for integer similarity scores?

**Comment by manuelaguadomtz** [comment]
Hi Monica

Yes, that's right! Are you having problems with the package?

**Comment by MonicaSai7** [comment]
Thanks! I was confused with the hformat parameter. This package is really helpful! We only need to change the ds_scores parameter to switch between similarity and dissimilarity scores right?

**Comment by manuelaguadomtz** [comment]
Yes, the **ds_scores** parameter is the only one you need to set to switch between similarity and dissimilarity scores.
